fork = false
frame = "full"
idle = true
maximized = true
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
mouse-cursor-icon = "arrow"
title-hidden = true
vsync = true
wsl = false

[font]
  size = 12
  hinting = 'full'
  edging = "antialias"
[[font.normal]]
  family = "RobotoMono Nerd Font"
  scale = 1
  weight = "Medium"
